### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by wxmerkt** [pal-robotics-forks/gazebo_ros_control#1]
Hi, 
Is this fork still actively required or can packages (e.g., `pal_hardware_gazebo`) be safely moved to the upstream https://github.com/ros-simulation/gazebo_ros_pkgs?

**Comment by v-lopez** [comment]
This package repository is not maintained and I will remove it now, but the you'll still need: https://github.com/pal-robotics-forks/gazebo_ros_pkgs
